# Generated by Django 6.0.6 on 2026-06-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='progstack_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
