# Generated by Django 6.0.6 on 2026-06-13 23:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whatsapp', '0003_whatsappbusinessnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('trial', 'Trial'), ('starter', 'Starter'), ('professional', 'Professional'), ('business', 'Business')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('max_conversations_per_month', models.IntegerField(default=100)),
                ('max_automation_rules', models.IntegerField(default=2)),
                ('max_whatsapp_numbers', models.IntegerField(default=1)),
                ('trial_days', models.IntegerField(default=0)),
                ('has_priority_support', models.BooleanField(default=False)),
                ('flutterwave_plan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trialing', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('fw_customer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('fw_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bitrix_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='whatsapp.bitrixaccount')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('conversations_used', models.PositiveIntegerField(default=0)),
                ('bitrix_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_summaries', to='whatsapp.bitrixaccount')),
            ],
            options={
                'unique_together': {('bitrix_account', 'period_start')},
            },
        ),
    ]
