# Generated by Django 6.0.6 on 2026-06-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0003_emaildomain_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildomain',
            name='verify_record_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emaildomain',
            name='verify_record_value',
            field=models.TextField(blank=True, default=''),
        ),
    ]
