# Generated by Django 6.0.6 on 2026-06-12 00:16

import apps.whatsapp.models.account
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitrixAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', apps.whatsapp.models.account.EncryptedTextField()),
                ('access_token', apps.whatsapp.models.account.EncryptedTextField()),
                ('refresh_token', apps.whatsapp.models.account.EncryptedTextField()),
                ('expires_at', models.DateTimeField()),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'expires_at'], name='whatsapp_bi_is_acti_fc7c63_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrmBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('lead', 'Lead'), ('contact', 'Contact'), ('deal', 'Deal')], max_length=20)),
                ('entity_id', models.CharField(max_length=50)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bitrix_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.bitrixaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('window_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bitrix_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.bitrixaccount')),
                ('crm_binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.crmbinding')),
            ],
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('whatsapp_template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('utility', 'Utility'), ('authentication', 'Authentication')], default='utility', max_length=20)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft (local only)'), ('pending', 'Pending Meta approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paused', 'Paused by Meta')], default='draft', max_length=20)),
                ('content', models.TextField()),
                ('variables', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bitrix_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.bitrixaccount')),
            ],
            options={
                'unique_together': {('bitrix_account', 'whatsapp_template_name', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='WebhookEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('bitrix', 'Bitrix24')], max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['processed', 'created_at'], name='whatsapp_we_process_d796da_idx'), models.Index(fields=['source', 'event_type'], name='whatsapp_we_source_ef1a92_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bitrix_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='whatsapp.bitrixaccount')),
            ],
            options={
                'unique_together': {('bitrix_account', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=10)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('sticker', 'Sticker'), ('location', 'Location'), ('contacts', 'Contacts'), ('template', 'Template'), ('unknown', 'Unknown')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('media_id', models.CharField(blank=True, max_length=255, null=True)),
                ('media_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('media_mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('bitrix_activity_id', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bitrix_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.bitrixaccount')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.conversation')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.whatsappcontact')),
            ],
        ),
        migrations.AddField(
            model_name='crmbinding',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_bindings', to='whatsapp.whatsappcontact'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='whatsapp.whatsappcontact'),
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trigger_event', models.CharField(choices=[('message_received', 'Message received'), ('message_sent', 'Message sent'), ('lead_created', 'Lead created'), ('deal_stage_changed', 'Deal stage changed')], max_length=50)),
                ('conditions', models.JSONField(default=dict)),
                ('action', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bitrix_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.bitrixaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['bitrix_account', 'trigger_event', 'is_active'], name='whatsapp_au_bitrix__05401a_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('bitrix_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.bitrixaccount')),
                ('message_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_source', to='whatsapp.messagelog')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.messagetemplate')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.whatsappcontact')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='whatsapp_ou_status_1d243a_idx'), models.Index(fields=['bitrix_account', 'status'], name='whatsapp_ou_bitrix__29ee99_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('bitrix_account', 'idempotency_key'), name='unique_outbound_idempotency')],
            },
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['timestamp'], name='whatsapp_me_timesta_686440_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['conversation', 'timestamp'], name='whatsapp_me_convers_261b73_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['contact', 'timestamp', 'direction'], name='whatsapp_me_contact_cfd940_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagelog',
            constraint=models.UniqueConstraint(condition=models.Q(('message_id__isnull', False)), fields=('bitrix_account', 'message_id'), name='unique_message_per_account'),
        ),
        migrations.AddIndex(
            model_name='crmbinding',
            index=models.Index(fields=['bitrix_account', 'entity_type', 'entity_id'], name='whatsapp_cr_bitrix__670b43_idx'),
        ),
        migrations.AddConstraint(
            model_name='crmbinding',
            constraint=models.UniqueConstraint(fields=('bitrix_account', 'entity_type', 'entity_id', 'contact'), name='unique_binding_per_entity'),
        ),
        migrations.AddConstraint(
            model_name='crmbinding',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('contact',), name='one_primary_binding_per_contact'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['contact', 'is_open'], name='whatsapp_co_contact_e46814_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_open', 'window_expires_at'], name='whatsapp_co_is_open_35bd53_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('bitrix_account', 'contact'), name='one_open_conversation_per_contact'),
        ),
    ]
