# Generated by Django 6.0.6 on 2026-06-13 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrixaccount',
            name='domain',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9-]+\\.bitrix24\\.[a-z.]+$')]),
        ),
    ]
