# Generated by Django 6.0.6 on 2026-06-16 03:26

import apps.accounts.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitrixConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', apps.accounts.fields.EncryptedTextField()),
                ('access_token', apps.accounts.fields.EncryptedTextField()),
                ('refresh_token', apps.accounts.fields.EncryptedTextField()),
                ('expires_at', models.DateTimeField()),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitrix_connection', to='accounts.account')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'expires_at'], name='bitrix_bitr_is_acti_ad643d_idx')],
            },
        ),
    ]
